### PR TITLE
The installation guide need to be chnaged as per this PR. Just a mino…

### PR DESCRIPTION
**Pull request by tharun143**
…r change in README.md

Signed-off-by: tharun143 <tharunravuri2000@gmail.com>

### CODE REVIEW

**Comment by tharun143** [comment]
@valeriocos now the checks have all passed. I hope this PR #107 will give you the solution for #106 issue.

**Comment by valeriocos** [comment]
Hi @tharun143 , thank you for the PR. Why `pip3 install .` has been removed?

**Comment by tharun143** [comment]
@valeriocos pip3 install . doesn't work.

**Comment by valeriocos** [comment]
The setup.py is in `django-hatstall`, please check if the steps below work for you, thanks

```
$ cd /tmp/
/tmp$ python3 -m venv test-hatstall
/tmp$ source test-hatstall/bin/activate
(test-hatstall) ~$ cd grimoirelab-hatstall/
(test-hatstall) ~/grimoirelab-hatstall$ pip install -r requirements.txt 
(test-hatstall) ~/grimoirelab-hatstall$ cd django-hatstall
(test-hatstall) ~/grimoirelab-hatstall/django-hatstall$ pip install .
```

**Comment by tharun143** [comment]
@valeriocos 
Screenshot from 2020-05-12 15-29-02

I did what u said to run through a virtual environment and even I have installed python3.7 it is still asking for python >= 3.6. What's wrong with this? Okay after installation how do you even set up because there is no manage.py file in the repo.

**Comment by valeriocos** [comment]
The error should be due to the fact that your virtual environment isn't python 3.6. Try the following
```
(test-hatstall) ~$ python --version
Python 3.6.9 <----- you should have something like this or Python 3.7
```

In order to create a virtual env with a specific Python version you should do something similar to the command below. This example assumes that python3.5 is installed in the machine:
```
python3.5 -m venv <my-env>
```

Once you have done this, please repeat the steps at https://github.com/chaoss/grimoirelab-hatstall/pull/107#issuecomment-627210949.
In https://github.com/chaoss/grimoirelab-hatstall/blob/master/django-hatstall/django_hatstall/settings.py#L26, you should fill the secret key:
```
SECRET_KEY = 'u1*y8wy#a!tahh!lj0fk6n)22%0_g$y-8r5q_13gf_!i8veswq'
```

Then you should execute:
```
(test-hatstall) ~/grimoirelab-hatstall/django-hatstall$ python3 manage.py createsuperuser
(test-hatstall) ~/grimoirelab-hatstall/django-hatstall$ python3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
May 12, 2020 - 10:30:06
Django version 3.0.6, using settings 'django_hatstall.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

If you access to http://127.0.0.1:8000/ you wil be asked to log in and the info needed to access the sortinghat database

**Comment by tharun143** [comment]
I tried to reinstall python3 and deleted the python dependencies :( which made me to lost ubuntu today.

**Comment by valeriocos** [comment]
Let me know how I can help you

**Comment by tharun143** [comment]
@valeriocos Right now I am trying to install wsl and Linux distro in windows after the successful installation I will get back to this installation. Thanks for asking. :)

**Comment by valeriocos** [comment]
Good luck! If this can be of any help, https://www.virtualbox.org/ can be a good option to install Linux on Windows

**Comment by tharun143** [comment]
@valeriocos This is showing there is no sorting hat module
Screenshot (146)

**Comment by valeriocos** [comment]
Hi @tharun143 , did you execute `pip3 -r requirements.txt` (Sortinghat should be installed with that command)?

**Comment by tharun143** [comment]
@valeriocos I installed all the requirements but the dulwich failed and something pooped up atlast. 
Screenshot (147)

Screenshot (148)

**Comment by valeriocos** [comment]
Sorry for the late reply @tharun143, it seems that your machine misses `gnu-gcc-install` (it's a debian package). The info at https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/ could be useful.

**Comment by tharun143** [comment]
@valeriocos Yes the installation was successful but when I tried to access profiles or organizations it is redirecting me to error.

Screenshot (150)

What should I have to do with this and I would like to use this experience and want to write the proper installation guide for hatstall. What do you say?

**Comment by valeriocos** [comment]
Sorry for the late reply @tharun143 !

It seems that you don't have mysql running. 

When starting HatStall you are requested to connect to a [SortingHat](https://github.com/chaoss/grimoirelab-sortinghat) db (name of the db, host, username, etc.), which is a tool built around a mysql db. The gif below shows how to connect to an existing SortingHat db (test_sh, which is empty).

Peek 15-05-2020 22-13

The sortinghat db can be initialized from the command line (`sortinghat init <your_db>`, ref https://github.com/chaoss/grimoirelab-sortinghat#configuration), then you can add identities following the basic commands at https://github.com/chaoss/grimoirelab-sortinghat#basic-commands (you can achieve an equivalent results using the API: https://github.com/chaoss/grimoirelab-sortinghat#basic-api-calls)

Below you can find the step to create a SortingHat DB (SortingHat should be already available in your machine) and to check that this db is visible in MySQL.
```
(lmn) slimbook@slimbook-KATANA:/tmp/grimoirelab-sortinghat$ sortinghat init my_fantastic_sh
(lmn) slimbook@slimbook-KATANA:/tmp/grimoirelab-sortinghat$ mysql -u root -p --host 127.0.0.1
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 21
Server version: 5.5.5-10.0.38-MariaDB-1~xenial mariadb.org binary distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| my_fantastic_sh    | <------
| mysql              |
| performance_schema |
| test_projects      |
| test_sh            |
+--------------------+
6 rows in set (0.00 sec)

mysql> 
```

> I would like to use this experience and want to write the proper installation guide for hatstall. What do you say?

It would be awesome, thanks! Let me know how I can help you

**Comment by tharun143** [comment]
@valeriocos I tried using the init of the database in my PC. but it doesn't work and threw an error. BTW instead of commenting here can I know your handle name in kiwi IRC. So I could chat there.
Screenshot (153)

**Comment by valeriocos** [comment]
Hi @tharun143 , GrimoireLab has an IRC channel (#grimoirelab on freenode, ref https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#irc-channel). Please write to me there, thanks

**Comment by valeriocos** [comment]
Hi @tharun143 let me know how you prefer to communicate to advance with this pull request. I saw your message on IRC yesterday, but when I answered you had already left.
```
9:40 * tharun (9d2cc367@157.44.195.103) has joined
<tharun> hello, this is tharun. Is this valcerios
9:48 * tharun has quit (Remote host closed the connection)
9:52 <valcos> Hi Tharun, how are you doing?
```

Please let me know a time interval when you plan to be connected to IRC, thanks

**Comment by tharun143** [comment]
@valeriocos I tried installing docker-engine in my pc. But stuck in choosing a version. Can you help me in figuring out this problem?
https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

**Comment by valeriocos** [comment]
Hi @tharun143 , please execute the following command in your machine:
```
slimbook@slimbook-KATANA:~$ uname -m
x86_64
```

The value returned there will help you to select the version. For the example above, it will be `x86_64 / amd64`.

Details about the `uname` command are at https://www.fastwebhost.in/blog/how-to-find-if-linux-is-running-on-32-bit-or-64-bit/

Hope this helps

**Comment by tharun143** [comment]
@valeriocos All the versions are amd64 and I am confused to choose which one.

**Comment by tharun143** [comment]
@valeriocos These are the versions available

docker-ce | 5:19.03.9~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.8~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.7~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.6~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.5~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.4~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.3~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.2~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.1~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:19.03.0~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.9~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.8~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.7~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.6~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.5~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.4~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.3~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.2~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.1~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 5:18.09.0~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 18.06.3~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 18.06.2~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 18.06.1~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 18.06.0~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
 docker-ce | 18.03.1~ce~3-0~ubuntu | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages

**Comment by valeriocos** [comment]
Hi @tharun143 ,

The command below will tell you your OS version (details [here](https://www.cyberciti.biz/faq/how-to-check-os-version-in-linux-command-line/)). This should help you to know the version to install. If you find it convenient, we can meet on IRC and try to resolve these installation problems.
```
~/Escritorio/sources/perceval$  cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by tharun143** [comment]
I was having the same version as yours. but there is no version for 18,04.4 LTS. So, I am confused to select which version. @valeriocos BTW I tried messaging you in the IRC.

**Comment by valeriocos** [comment]
Hi @tharun143 ! It seems that we are not able to meet each other on IRC (when I'm connected, you are not and viceversa). If you find it convenient, we can organize a call (send an email to valcos@bitergia.com to discuss the details), thanks.

**Comment by tharun143** [comment]
ERROR: Command errored out with exit status 1:
   command: /tmp/test-hatstall/bin/python3 /tmp/test-hatstall/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5bjxozvg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"''
       cwd: None
  Complete output (304 lines):
  Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Collecting wheel
    Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
  Collecting setuptools
    Using cached setuptools-46.4.0-py3-none-any.whl (583 kB)
  Collecting Cython
    Using cached Cython-0.29.19-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
  Collecting numpy==1.13.1
    Using cached numpy-1.13.1.zip (5.0 MB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (setup.py): started
    Building wheel for numpy (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /tmp/test-hatstall/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-22utovjd
         cwd: /tmp/pip-install-85p9ti_x/numpy/
    Complete output (9 lines):
    Running from numpy source directory.
    /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/misc_util.py:469: SyntaxWarning: "is" with a literal. Did you mean "=="?
      return is_string(s) and ('*' in s or '?' is s)
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
  
    error: invalid command 'bdist_wheel'
    ----------------------------------------
    ERROR: Failed building wheel for numpy
    Running setup.py clean for numpy
    ERROR: Command errored out with exit status 1:
     command: /tmp/test-hatstall/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
         cwd: /tmp/pip-install-85p9ti_x/numpy
    Complete output (10 lines):
    Running from numpy source directory.
  
    `setup.py clean` is not supported, use one of the following instead:
  
      - `git clean -xdf` (cleans all files)
      - `git clean -Xdf` (cleans all versioned files, doesn't touch
                          files that aren't checked into the git repo)
  
    Add `--force` to your command to use it anyway if you must (unsupported).
  
    ----------------------------------------
    ERROR: Failed cleaning build dir for numpy
  Failed to build numpy
  Installing collected packages: wheel, setuptools, Cython, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /tmp/test-hatstall/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5zvw2lry/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-5bjxozvg/overlay --compile --install-headers /tmp/test-hatstall/include/site/python3.8/numpy
           cwd: /tmp/pip-install-85p9ti_x/numpy/
      Complete output (249 lines):
      Running from numpy source directory.
  
      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:
  
        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)
  
  
      blas_opt_info:
      blas_mkl_info:
        libraries mkl_rt not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      blis_info:
        libraries blis not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      openblas_info:
        libraries openblas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_blas_info:
        libraries satlas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/system_info.py:572: UserWarning:
          Atlas (http://math-atlas.sourceforge.net/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [atlas]) or by setting
          the ATLAS environment variable.
        self.calc_info()
      blas_info:
        libraries blas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/system_info.py:572: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE
  
      /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/system_info.py:572: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE
  
      /bin/sh: 1: svnversion: not found
      non-existing path in 'numpy/distutils': 'site.cfg'
      /bin/sh: 1: svnversion: not found
      F2PY Version 2
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      openblas_lapack_info:
        libraries openblas not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas,tatlas not found in /tmp/test-hatstall/lib
        libraries lapack_atlas not found in /tmp/test-hatstall/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/lib64
        libraries lapack_atlas not found in /usr/lib64
        libraries tatlas,tatlas not found in /usr/lib
        libraries lapack_atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
  
      atlas_3_10_info:
        libraries satlas,satlas not found in /tmp/test-hatstall/lib
        libraries lapack_atlas not found in /tmp/test-hatstall/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/lib64
        libraries lapack_atlas not found in /usr/lib64
        libraries satlas,satlas not found in /usr/lib
        libraries lapack_atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE
  
      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in /tmp/test-hatstall/lib
        libraries lapack_atlas not found in /tmp/test-hatstall/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
        libraries lapack_atlas not found in /usr/lib64
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
        libraries lapack_atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE
  
      atlas_info:
        libraries f77blas,cblas,atlas not found in /tmp/test-hatstall/lib
        libraries lapack_atlas not found in /tmp/test-hatstall/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/lib64
        libraries lapack_atlas not found in /usr/lib64
        libraries f77blas,cblas,atlas not found in /usr/lib
        libraries lapack_atlas not found in /usr/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE
  
      lapack_info:
        libraries lapack not found in ['/tmp/test-hatstall/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib']
        NOT AVAILABLE
  
      /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/system_info.py:572: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        self.calc_info()
      lapack_src_info:
        NOT AVAILABLE
  
      /tmp/pip-install-85p9ti_x/numpy/numpy/distutils/system_info.py:572: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE
  
      /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.linux-x86_64-3.8
      creating build/src.linux-x86_64-3.8/numpy
      creating build/src.linux-x86_64-3.8/numpy/distutils
      building library "npymath" sources
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize IntelFCompiler
      Could not locate executable ifort
      Could not locate executable ifc
      customize LaheyFCompiler
      Could not locate executable lf95
      customize PGroupFCompiler
      Could not locate executable pgfortran
      customize AbsoftFCompiler
      Could not locate executable f90
      Could not locate executable f77
      customize NAGFCompiler
      customize VastFCompiler
      customize CompaqFCompiler
      Could not locate executable fort
      customize IntelItaniumFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize IntelEM64TFCompiler
      customize GnuFCompiler
      Could not locate executable g77
      customize G95FCompiler
      Could not locate executable g95
      customize PathScaleFCompiler
      Could not locate executable pathf95
      don't know how to compile Fortran code on platform 'posix'
      C compiler: x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
  
      compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/tmp/test-hatstall/include -I/usr/include/python3.8 -c'
      x86_64-linux-gnu-gcc: _configtest.c
      /bin/bash: x86_64-linux-gnu-gcc: command not found
      /bin/bash: x86_64-linux-gnu-gcc: command not found
      failure.
      removing: _configtest.c _configtest.o
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-85p9ti_x/numpy/setup.py", line 392, in <module>
          setup_package()
        File "/tmp/pip-install-85p9ti_x/numpy/setup.py", line 384, in setup_package
          setup(**metadata)
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/tmp/test-hatstall/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/install.py", line 62, in run
          r = self.setuptools_run()
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
          return distutils_install.run(self)
        File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
          self.run_command('build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/build.py", line 47, in run
          old_build.run(self)
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/build_src.py", line 148, in run
          self.build_sources()
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
          self.build_library_sources(*libname_info)
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "/tmp/pip-install-85p9ti_x/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 674, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /tmp/test-hatstall/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-85p9ti_x/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5zvw2lry/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-5bjxozvg/overlay --compile --install-headers /tmp/test-hatstall/include/site/python3.8/numpy Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/test-hatstall/bin/python3 /tmp/test-hatstall/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-5bjxozvg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython 'numpy==1.9.3; python_version=='"'"'3.5'"'"'' 'numpy==1.12.1; python_version=='"'"'3.6'"'"'' 'numpy==1.13.1; python_version>='"'"'3.7'"'"'' Check the logs for full command output.
@valeriocos  THis is the entire error :p

**Comment by valeriocos** [comment]
Hi @tharun143 ,

The problem seems related to the python version in use (python 3.8), can you try to install it on python 3.5 or 3.6 (https://github.com/chaoss/grimoirelab-hatstall/blob/master/django-hatstall/setup.py#L35)? thanks

**Pull request closed without merging**
